#========================================spring config=====================================  
spring:
  profiles:
    active: dev
  application:
    name: base-blog
  devtools:
    remote:
      restart:
        enabled: false
#========================================mybatis config=====================================
mybatis:
  type-aliases-package: com.sly.blog.base.blog.model
  mapper-locations: classpath:mapper/*.xml
