#========================================server config=====================================
server:
  port: 8300
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/